name: HyperPickaxe
version: '${project.version}'
main: me.hyperburger.pickaxe3.HyperPickaxe
api-version: '1.13'
commands:
  givepickaxe:
    permission: hyperpickaxe.give
    description: Give a custom pickaxe with specified attributes.
    usage: /givepickaxe <material> <displayName> <width> <height> <depth>