name: HyperPickaxe
version: '1.02'
main: me.hyperburger.pickaxe3.HyperPickaxe
api-version: '1.21'
commands:
  givepickaxe:
    permission: hyperpickaxe.give
    description: Give a custom pickaxe with specified attributes.
    usage: /givepickaxe <material> <displayName> <width> <height> <depth>